# 说明:
# 1、未注释的都是必填项
# 2、英文 : 后要空一格, domains 和 tips 里的 - 代表分组, 不可省略

domain: 2bi.xyz
title: 二逼米表
#donate: 可选, 打赏链接, 完整的可访问链接

# 对应四种颜色, 尽量选择 #123456 这种样式
color:
  default: red
  reserved: orange
  onsale: green
  sold: gray

# true: 标签模式, false: 文本模式
badge: false

# 域名列表
# url 可选, domain 超链接地址, 比如议价的话可跳转到自定义的报价页面
# price 可选，但建议都写上，自定义内容，不一定是数字
# 非卖品
reserved-domains:
  - domain: domain.kids
    url: https://domain.kids
    description: 域名
    price: 非卖品
# 出售中
onsale-domains:
  - domain: vip.kids
    description: vip
    price: $888
  - domain: top.kids
    description: top
    price: 议价
  - domain: dns.kids
    description: dns
    price: ￥666
  - domain: life.kids
    description: life
    price: 自定义
# 已售出
sold-domains:
  - domain: qifei.xyz
    description: 暂无
    price: 已出售

# 其他说明
# url: 可选, title 超链接地址
# price: 可选，自定义内容，不一定是数字
tips:
  - title: 友链说明
    description: 申请加入米表联盟请发送邮件

# 联系方式
# url 可选, 超链接地址
contacts:
  - type: QQ
    text: 254081150
  - type: Email
    text: viplink@foxmail.com
    url: mailto:viplink@foxmail.com
  - type: 微信
    text: xinyuzhoucom

# 米表联盟
links:
  - url: http://2bi.cc
    description: 二逼米表
